env:
  tenantId: 00000000-0000-0000-0000-000000000000
  subscriptionId: 00000000-0000-0000-0000-000000000000
  artifactsPath: ${{ github.workspace }}/artifacts
  tempPath: ${{ env.Agent.TempDirectory }}/ymltemp
  archiveFile: archive.zip
  pipelinesPath: ${{ github.workspace }}/pipelines
  infrastructurePath: ${{ github.workspace }}/infrastructure
  testsPath: ${{ github.workspace }}/tests
  srcPath: ${{ github.workspace }}/src
  scriptsPath: ${{ github.workspace }}/scripts
  buildConfiguration: Release
