on:
  push:
    branches:
    - '*'
    paths:
    - .azure/*
  pull-request:
    branches-ignore:
    - '*'
env:
  subscriptionService: AZURE_DEVOPS_SERVICE_CONNECTION
  appcsConnection: ${{ env.appcsConnection }}
  template: ../variables/common.yml
  - name: appcsKeys
    type: object
    default: [ "Shared:Sentinel", "ConnectionStrings:StorageTables" ]
  - name: appcsValues
    type: object
    default: [ "1", "$(stConnection)" ]
jobs:
  development_Stage_deploy_landing_zone:
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/landingzone-infrastructure-steps.yml
        armPath: ${{ env.armPath }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionService: ${{ env. parameters.subscriptionService  }}
        rgName: ${{ env.rgName }}
        rgLocation: ${{ env.rgLocation }}
        appiName: ${{ env.appiName }}
        kvName: ${{ env.kvName }}
        stName: ${{ env.stName }}
        workName: ${{ env.workName }}
  development_Stage_deploy_appcs_infrastructure:
    needs:
    - development_Stage_deploy_landing_zone
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/appcs-infrastructure-steps.yml
        armPath: ${{ env.armPath }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionService: ${{ env. parameters.subscriptionService  }}
        rgName: ${{ env.rgName }}
        rgLocation: ${{ env.rgLocation }}
        appcsName: ${{ env.appcsName }}
        appcsSku: ${{ env.appcsSku }}
  development_Stage_deploy_appcs_settings:
    needs:
    - development_Stage_deploy_appcs_infrastructure
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/appcs-settings-steps.yml
        armPath: ${{ env.armPath }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionService: ${{ env. parameters.subscriptionService  }}
        rgName: ${{ env.rgName }}
        appcsName: ${{ env.appcsName }}
        appcsKeys: ${{ env. parameters.appcsKeys  }}
        appcsValues: ${{ env. parameters.appcsValues  }}
  production_Stage_deploy_landing_zone:
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/landingzone-infrastructure-steps.yml
        armPath: ${{ env.armPath }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionService: ${{ env. parameters.subscriptionService  }}
        rgName: ${{ env.rgName }}
        rgLocation: ${{ env.rgLocation }}
        appiName: ${{ env.appiName }}
        kvName: ${{ env.kvName }}
        stName: ${{ env.stName }}
        workName: ${{ env.workName }}
                    
