on:
  push:
    branches:
    - '*'
    paths:
    - src/*
  pull-request:
    branches-ignore:
    - '*'
env:
  template: ../variables/common.yml
  nugetService: COMPANY-nuget-001
  nugetId: ${{ env.nugetId }}
  versionToReplace: 1.0.0
jobs:
  development_Stage_build_src:
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        scriptsPath: ${{ env.scriptsPath }}
        srcPath: ${{ env.srcPath }}
  development_Stage_test_src:
    needs:
    - development_Stage_build_src
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-test-steps.yml
        testPath: ${{ github.workspace }}/src
        arguments: --filter TestCategory!=Integration
        appcsEnvironmentVariable: ${{ env. parameters.appcsEnvironmentVariable  }}
        appcsConnection: ${{ env. parameters.appcsConnection  }}
        rgEnvironment: ${{ env.rgEnvironment }}
  development_Stage_pack_src:
    needs:
    - development_Stage_test_src
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-pack-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        scriptsPath: ${{ env.scriptsPath }}
        srcPath: ${{ env.srcPath }}
        versionToReplace: ${{ env. parameters.versionToReplace  }}
  development_Stage_deploy_nuget:
    needs:
    - development_Stage_pack_src
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/nuget-deploy-internal-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        nugetId: ${{ env. parameters.nugetId  }}
  production_Stage_build_src:
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        scriptsPath: ${{ env.scriptsPath }}
        srcPath: ${{ env.srcPath }}
  production_Stage_test_src:
    needs:
    - production_Stage_build_src
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-test-steps.yml
        testPath: ${{ github.workspace }}/src
        arguments: --filter TestCategory!=Integration
        appcsEnvironmentVariable: ${{ env. parameters.appcsEnvironmentVariable  }}
        appcsConnection: ${{ env. parameters.appcsConnection  }}
        rgEnvironment: ${{ env.rgEnvironment }}
  production_Stage_pack_src:
    needs:
    - production_Stage_test_src
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-pack-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        scriptsPath: ${{ env.scriptsPath }}
        srcPath: ${{ env.srcPath }}
        versionToReplace: ${{ env. parameters.versionToReplace  }}
  production_Stage_deploy_nuget:
    needs:
    - production_Stage_pack_src
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/nuget-deploy-external-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        nugetService: ${{ env. parameters.nugetService  }}
                    