on:
  push:
    branches:
    - '*'
    paths:
    - tests/*
  pull-request:
    branches-ignore:
    - '*'
env:
  template: ../variables/development.yml
  buildPlatform: Any CPU
  buildConfiguration: Release
jobs:
  development_Stage_test_integration:
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/integration-test-steps.yml
        integrationPath: ${{ env.integrationPath }}
        appcsEnvironmentVariable: ${{ env.appcsEnvironmentVariable }}
        appcsConnection: ${{ env.appcsConnection }}
        stEnvironmentVariable: ${{ env.stEnvironmentVariable }}
        stConnection: ${{ env.stConnection }}
        rgEnvironment: ${{ env.rgEnvironment }}
                    