on:
  push:
    branches:
    - '*'
    paths:
    - src/*
  pull-request:
    branches-ignore:
    - '*'
env:
  appcsEnvironmentVariable: AZURE_APP_CONFIGURATION_CONNECTION
  appcsConnection: ${{ env.appcsConnection }}
  template: ../variables/common.yml
jobs:
  development_Stage_build_src:
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/dotnet-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        srcPath: ${{ env.srcPath }}
  development_Stage_test_src:
    needs:
    - development_Stage_build_src
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-test-steps.yml
        testPath: ${{ github.workspace }}/src
        appcsEnvironmentVariable: ${{ env.appcsEnvironmentVariable }}
        appcsConnection: ${{ env.appcsConnection }}
        rgEnvironment: ${{ env.rgEnvironment }}
  development_Stage_build_func:
    needs:
    - development_Stage_test_src
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/func-build-steps.yml
        archiveFile: ${{ env.funcArchiveFile }}
        funcPath: ${{ env.funcPath }}
        tempPath: ${{ env.tempPath }}
  development_Stage_deploy_func:
    needs:
    - development_Stage_build_func
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/func-deploy-steps.yml
        appSettings: -${{ env.appcsEnvironmentVariable }} ${{ env.appcsConnection }} -${{ env.stEnvironmentVariable }} ${{ env.stConnection }} -APPINSIGHTS_INSTRUMENTATIONKEY ${{ env.appiKey }} -APPLICATIONINSIGHTS_CONNECTION_STRING ${{ env.appiConnection }} -AZURE_FUNCTIONS_ENVIRONMENT ${{ env.rgEnvironment }} -ASPNETCORE_ENVIRONMENT ${{ env.rgEnvironment }} 
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.funcArchiveFile }}
        funcName: ${{ env.funcName }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionService: ${{ env. parameters.subscriptionService  }}
  development_Stage_build_webjob:
    needs:
    - development_Stage_test_src
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/webjob-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.webjobArchiveFile }}
        srcPath: ${{ env.srcPath }}
        webjobProject: ${{ env.webjobProject }}
        webjobName: ${{ env.webjobName }}
        cronSchedule: ${{ env.webjobSchedule }}
  development_Stage_deploy_webjob:
    needs:
    - development_Stage_build_webjob
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/web-deploy-steps.yml
        appSettings: -${{ env.appcsEnvironmentVariable }} ${{ env.appcsConnection }} -${{ env.stEnvironmentVariable }} ${{ env.stConnection }} -AzureWebJobsDashboard ${{ env.stConnection }} -APPINSIGHTS_INSTRUMENTATIONKEY ${{ env.appiKey }} -APPLICATIONINSIGHTS_CONNECTION_STRING ${{ env.appiConnection }} -AZURE_FUNCTIONS_ENVIRONMENT ${{ env.rgEnvironment }} -ASPNETCORE_ENVIRONMENT ${{ env.rgEnvironment }} 
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.webjobArchiveFile }}
        webName: ${{ env.webjobName }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionService: ${{ env. parameters.subscriptionService  }}
  production_Stage_build_src:
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        srcPath: ${{ env.srcPath }}
  production_Stage_test_src:
    needs:
    - production_Stage_build_src
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/dotnet-test-steps.yml
        testPath: ${{ github.workspace }}/src
        appcsEnvironmentVariable: ${{ env.appcsEnvironmentVariable }}
        appcsConnection: ${{ env.appcsConnection }}
        rgEnvironment: ${{ env.rgEnvironment }}
  production_Stage_build_func:
    needs:
    - production_Stage_test_src
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/func-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.funcArchiveFile }}
        funcPath: ${{ env.funcPath }}
        tempPath: ${{ env.tempPath }}
  production_Stage_deploy_func:
    needs:
    - production_Stage_build_func
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/func-deploy-steps.yml
        appSettings: -${{ env.appcsEnvironmentVariable }} ${{ env.appcsConnection }} -${{ env.stEnvironmentVariable }} ${{ env.stConnection }} -APPINSIGHTS_INSTRUMENTATIONKEY ${{ env.appiKey }} -APPLICATIONINSIGHTS_CONNECTION_STRING ${{ env.appiConnection }} -AZURE_FUNCTIONS_ENVIRONMENT ${{ env.rgEnvironment }} -ASPNETCORE_ENVIRONMENT ${{ env.rgEnvironment }} 
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.funcArchiveFile }}
        funcName: ${{ env.funcName }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionService: ${{ env. parameters.subscriptionService  }}
  production_Stage_build_webjob:
    needs:
    - production_Stage_test_src
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/webjob-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.webjobArchiveFile }}
        srcPath: ${{ env.srcPath }}
        webjobProject: ${{ env.webjobProject }}
        webjobName: ${{ env.webjobName }}
        cronSchedule: ${{ env.webjobSchedule }}
  production_Stage_deploy_webjob:
    needs:
    - production_Stage_build_webjob
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - 
      run: |
        #../steps/web-deploy-steps.yml
        appSettings: -${{ env.appcsEnvironmentVariable }} ${{ env.appcsConnection }} -${{ env.stEnvironmentVariable }} ${{ env.stConnection }} -AzureWebJobsDashboard ${{ env.stConnection }} -APPINSIGHTS_INSTRUMENTATIONKEY ${{ env.appiKey }} -APPLICATIONINSIGHTS_CONNECTION_STRING ${{ env.appiConnection }} -AZURE_FUNCTIONS_ENVIRONMENT ${{ env.rgEnvironment }} -ASPNETCORE_ENVIRONMENT ${{ env.rgEnvironment }} 
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.webjobArchiveFile }}
        webName: ${{ env.webjobName }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionService: ${{ env. parameters.subscriptionService  }}
                    