on:
  push:
    branches:
    - '*'
    paths:
    - src/*
  pull-request:
    branches-ignore:
    - '*'
env:
  template: ../variables/development.yml
  buildPlatform: Any CPU
  buildConfiguration: Release
#  - name: workerSettings
#    type: object
#    default: 
#      - name: 'APPINSIGHTS_INSTRUMENTATIONKEY'
#        value: '$(appiKey)'
#        slotSetting: false
#      - name: 'APPLICATIONINSIGHTS_CONNECTION_STRING'
#        value: '$(appiConnection)'
#        slotSetting: false        
#      - name: 'ASPNETCORE_ENVIRONMENT'
#        value: '$(rgEnvironment)'
#        slotSetting: false
#      - name: 'AzureWebJobsDashboard'
#        value: '$(stConnection)'
#        slotSetting: false
#      - name: '$(appcsEnvironmentVariable)'
#        value: '$(appcsConnection)'
#        slotSetting: false
#      - name: '$(stEnvironmentVariable)'
#        value: '$(stConnection)'
#        slotSetting: false

jobs:
  development_Stage_build_webjob:
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/webjob-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.archiveFile }}
        srcPath: ${{ env.webjobPath }}
        webjobName: ${{ env.webjobName }}
        cronSchedule: ${{ env.webjobSchedule }}
  development_Stage_test_webjob:
    needs:
    - development_Stage_build_webjob
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/dotnet-test-steps.yml
        unitPath: ${{ env.webjobPath }}
        rgEnvironment: ${{ env.rgEnvironment }}
        appcsEnvironmentVariable: ${{ env.appcsEnvironmentVariable }}
        appcsConnection: ${{ env.appcsConnection }}
        stEnvironmentVariable: ${{ env.stEnvironmentVariable }}
        stConnection: ${{ env.stConnection }}
  development_Stage_settings_webjob:
    needs:
    - development_Stage_build_webjob
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/webjob-settings-steps.yml
        subscriptionName: ${{ env.subscriptionName }}
        rgEnvironment: ${{ env.rgEnvironment }}
        webjobName: ${{ env.webjobName }}
        appSettings: ${{ env. parameters.workerSettings  }}
  development_Stage_deploy_webjob:
    needs:
    - development_Stage_settings_webjob
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/webjob-deploy-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.archiveFile }}
        webjobName: ${{ env.webjobName }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionName: ${{ env.subscriptionName }}
  production_Stage_build_webjob:
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/webjob-build-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.archiveFile }}
        srcPath: ${{ env.webjobPath }}
        webjobName: ${{ env.webjobName }}
        cronSchedule: ${{ env.webjobSchedule }}
  production_Stage_test_webjob:
    needs:
    - production_Stage_build_webjob
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/dotnet-test-steps.yml
        unitPath: ${{ env.webjobPath }}
        rgEnvironment: ${{ env.rgEnvironment }}
        appcsEnvironmentVariable: ${{ env.appcsEnvironmentVariable }}
        appcsConnection: ${{ env.appcsConnection }}
        stEnvironmentVariable: ${{ env.stEnvironmentVariable }}
        stConnection: ${{ env.stConnection }}
  production_Stage_settings_webjob:
    needs:
    - production_Stage_build_webjob
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/webjob-settings-steps.yml
        subscriptionName: ${{ env.subscriptionName }}
        rgEnvironment: ${{ env.rgEnvironment }}
        webjobName: ${{ env.webjobName }}
        appSettings: ${{ env. parameters.workerSettings  }}
  production_Stage_deploy_webjob:
    needs:
    - production_Stage_settings_webjob
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/webjob-deploy-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.archiveFile }}
        webjobName: ${{ env.webjobName }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionName: ${{ env.subscriptionName }}
