on:
  push:
    branches:
    - '*'
    paths:
    - src/*
  pull-request:
    branches-ignore:
    - '*'
env:
  template: ../variables/development.yml
  buildPlatform: Any CPU
  buildConfiguration: Release
jobs:
  development_Stage_build_func:
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/func-build-steps.yml
        archiveFile: ${{ env.archiveFile }}
        funcPath: ${{ env.funcPath }}
        tempPath: ${{ env.tempPath }}
  development_Stage_test_func:
    needs:
    - development_Stage_build_func
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/dotnet-test-steps.yml
        unitPath: ${{ env.funcPath }}
        rgEnvironment: ${{ env.rgEnvironment }}
        appcsEnvironmentVariable: ${{ env.appcsEnvironmentVariable }}
        appcsConnection: ${{ env.appcsConnection }}
        stEnvironmentVariable: ${{ env.stEnvironmentVariable }}
        stConnection: ${{ env.stConnection }}
  development_Stage_settings_func:
    needs:
    - development_Stage_build_func
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/func-settings-steps.yml
        subscriptionName: ${{ env.subscriptionName }}
        rgEnvironment: ${{ env.rgEnvironment }}
        funcName: ${{ env.funcName }}
  development_Stage_deploy_func:
    needs:
    - development_Stage_settings_func
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/func-deploy-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.archiveFile }}
        funcName: ${{ env.funcName }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionName: ${{ env.subscriptionName }}
  production_Stage_build_func:
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/func-build-steps.yml
        archiveFile: ${{ env.archiveFile }}
        funcPath: ${{ env.funcPath }}
        tempPath: ${{ env.tempPath }}
  production_Stage_test_func:
    needs:
    - production_Stage_build_func
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/dotnet-test-steps.yml
        unitPath: ${{ env.funcPath }}
        rgEnvironment: ${{ env.rgEnvironment }}
        appcsEnvironmentVariable: ${{ env.appcsEnvironmentVariable }}
        appcsConnection: ${{ env.appcsConnection }}
        stEnvironmentVariable: ${{ env.stEnvironmentVariable }}
        stConnection: ${{ env.stConnection }}
  production_Stage_settings_func:
    needs:
    - production_Stage_build_func
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/func-settings-steps.yml
        subscriptionName: ${{ env.subscriptionName }}
        rgEnvironment: ${{ env.rgEnvironment }}
        funcName: ${{ env.funcName }}
  production_Stage_deploy_func:
    needs:
    - production_Stage_settings_func
    env:
      template: ../variables/production.yml
    if: (github.ref == 'refs/heads/main')
    steps:
    - uses: actions/checkout@v2
    - run: |
        #../steps/func-deploy-steps.yml
        artifactsPath: ${{ env.artifactsPath }}
        archiveFile: ${{ env.archiveFile }}
        funcName: ${{ env.funcName }}
        subscriptionId: ${{ env.subscriptionId }}
        subscriptionName: ${{ env.subscriptionName }}
                    