trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - .azure/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: subscriptionService
    type: string 
    default: "gtc-entities-001"
  - name: subscriptionId
    type: string 
    default: "$(subscriptionId)"

variables:
  - template: ../variables/common.yml
      
stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/development-subjects.yml

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: ../steps/landingzone-infrastructure-steps.yml
            parameters:
              armPath: '$(armPath)'
              subscriptionId: '${{ parameters.subscriptionId }}'
              subscriptionService: '${{ parameters.subscriptionService }}'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workLocation: '$(rgLocation)'
              workName: '$(workName)'
              workResourceGroupName: '$(rgSharedName)'
              workSubscriptionId: '${{ parameters.subscriptionId }}'

          - template: ../steps/api-infrastructure-steps.yml
            parameters:
              armPath: '$(armPath)'
              subscriptionId: '${{ parameters.subscriptionId }}'
              subscriptionService: '${{ parameters.subscriptionService }}'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              rgEnvironment: '$(rgEnvironment)'
              planName: '$(planName)'
              planResourceGroupName: '$(rgSharedName)'
              planSku: '$(planSku)'
              planCapacity: '$(planCapacity)'
              apiName: '$(apiName)'
