trigger:
  batch: true
  branches:
    include:
    - '*'
  paths:
    include:
    - .azure/*

pr:
  branches:
    exclude:
    - '*'

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: subscriptionService
    type: string 
    default: "gtc-entities-001"
  - name: subscriptionId
    type: string 
    default: "$(subscriptionId)"

variables:
  - template: ../variables/common.yml
      
stages:
  - stage: development
    condition: ne(variables['Build.SourceBranch'], 'refs/heads/main')
    variables:
      - template: ../variables/development-entities.yml

    jobs:
      - job: deploy_landing_zone
        steps:
          - template: ../steps/landingzone-infrastructure-steps.yml
            parameters:
              armPath: '$(armPath)'
              subscriptionId: '${{ parameters.subscriptionId }}'
              subscriptionService: '${{ parameters.subscriptionService }}'
              rgName: '$(rgName)'
              rgLocation: '$(rgLocation)'
              appiName: '$(appiName)'
              kvName: '$(kvName)'
              stName: '$(stName)'
              workLocation: '$(rgLocation)'
              workName: '$(workName)'
              workResourceGroupName: '$(rgName)'
              workSubscriptionId: '$(subscriptionId)'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Validate $(planName)"
            inputs:
                deploymentScope: "Resource Group"
                azureResourceManagerConnection: "${{ parameters.subscriptionService }}"
                subscriptionId: '${{ parameters.subscriptionId }}'
                action: "Create Or Update Resource Group"
                resourceGroupName: '$(rgName)'
                location: '$(rgLocation)'
                templateLocation: "Linked artifact"
                csmFile: "$(armPath)/plan-appplan.json"        
                csmParametersFile: "$(armPath)/plan-appplan.parameters.json"        
                deploymentMode: "Validation"
                overrideParameters: -name "$(planName)" -sku "$(planSku)" -location '$(rgLocation)' -skuCapacity "4"

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: "Deploy $(planName)"
            inputs:
                deploymentScope: "Resource Group"
                azureResourceManagerConnection: "${{ parameters.subscriptionService }}"
                subscriptionId: '${{ parameters.subscriptionId }}'
                action: "Create Or Update Resource Group"
                resourceGroupName: '$(rgName)'
                location: '$(rgLocation)'
                templateLocation: "Linked artifact"
                csmFile: "$(armPath)/plan-appplan.json"
                csmParametersFile: "$(armPath)/plan-appplan.parameters.json"
                deploymentMode: "Incremental"
                overrideParameters: -name "$(planName)" -sku "$(planSku)" -location '$(rgLocation)' -skuCapacity "4"
