on:
  push:
    branches-ignore:
    - main
  pull_request:
    branches:
    - main    

env:
  API_NAME: 'api-subjects-dev-001'
  APPINSIGHTS_NAME: 'appi-subjects-dev-001'
  ARM_PATH: './.azure'
  AZURE_RG_ENVIRONMENT: 'Development'
  AZURE_RG_LOCATION: 'westus3'
  AZURE_RG_NAME: 'gtc-rg-subjects-dev-001'
  KEYVAULT_NAME: 'kv-subjects-dev-001'
  PLAN_NAME: 'plan-entities-dev-001'
  SHARED_RG_NAME: 'gtc-rg-entities-dev-001'
  STORAGE_NAME: 'stsubjectsdev001'
  WORKSPACE_NAME: 'work-entities-dev-001'  

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:  
  development_Stage_deploy_landing_zone:
    name: 'Deploy landing zone IaC'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: '${{ env.API_NAME }} Settings'
        id: settings
        uses: azure/appservice-settings@v1
      with:
        app-name: '${{ env.API_NAME }}'
        app-settings-json: '${{ secrets.APP_SETTINGS }}' 
        connection-strings-json: '${{ secrets.CONNECTION_STRINGS }}'
        #general-settings-json: '{"alwaysOn": "false", "webSocketsEnabled": "true"}' #'General configuration settings as Key Value pairs'      

# App settings
#[
#  {
#    "name": "APPINSIGHTS_INSTRUMENTATIONKEY",
#    "value": "<value-1>",
#    "slotSetting": false
#  },
#  {
#    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
#    "value": "<value-2>",
#    "slotSetting": false
#  },
#  {
#  "name": "APPCONFIGURATIONSTORE_CONNECTION_STRING",
#  "value": "<value-2>",
#  "slotSetting": false
#  },
#  {
#    "name": "ASPNETCORE_ENVIRONMENT",
#    "value": "<value-2>",
#    "slotSetting": false
#  }
#]

# Connection strings
#[
#  {
#    "name": "name-1",
#    "value": "conn-string-1",
#    "type": "SQLServer",
#    "slotSetting": false
#  },
#  {
#    "name": "name-2",
#    "value": "conn-string-2",
#    "type": "PostgreSQL",
#    "slotSetting": false
#  },
#]