on:
  push:
    branches:
    - main  
  pull_request:
    branches:
    - main    

env:
  armPath: './.azure'
  rgEnvironment: 'Development'
  rgName: 'rg-entities-dev-001'
  stName: 'stentitiesdev001'
  locationName: 'West US 3'


#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  security-events: write

jobs:  
  development_Stage_deploy_landing_zone:
    name: 'Deploy landing zone IaC'
    runs-on: ubuntu-latest
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Validate ${{ env.stName }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.rgName  }} --template-file ${{ env.armPath  }}/st-storageaccount.json --parameters  ${{ env.armPath  }}/st-storageaccount.parameters.json -name ${{ env.stName }}
