on:
  push:
    branches:
    - main  
  pull_request:
    branches:
    - main    

env:
  subscriptionService: AZURE_DEVOPS_SERVICE_CONNECTION
  template: ../variables/common.yml

#Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  security-events: write

jobs:  
  development_Stage_deploy_landing_zone:
    name: 'Deploy landing zone IaC'
    runs-on: ubuntu-latest
    env:
      template: ../variables/development.yml
    if: (github.ref != 'refs/heads/main')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Validate ${{ env.stName   }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.rgName  }} --template-file ${{ env.armPath  }}/st-storageaccount.json --parameters  ${{ env.armPath  }}/st-storageaccount.parameters.json -name "${{ env.stName   }}"
      - name: Deploy ${{ env.stName   }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.rgName  }} --template-file ${{ env.armPath  }}/st-storageaccount.json --parameters  ${{ env.armPath  }}/st-storageaccount.parameters.json -name "${{ env.stName   }}"
      - name: Validate ${{ env.workName   }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.workResourceGroupName  }} --template-file ${{ env.armPath  }}/work-loganalyticsworkspace.json --parameters  ${{ env.armPath  }}/work-loganalyticsworkspace.parameters.json -name "${{ env.workName   }}"
      - name: Deploy ${{ env.workName   }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.workResourceGroupName  }} --template-file ${{ env.armPath  }}/work-loganalyticsworkspace.json --parameters  ${{ env.armPath  }}/work-loganalyticsworkspace.parameters.json -name "${{ env.workName   }}"
      - name: Validate ${{ env.appiName  }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.rgName  }} --template-file ${{ env.armPath  }}/appi-applicationinsights.json --parameters  ${{ env.armPath  }}/appi-applicationinsights.parameters.json -name "${{ env.appiName  }}" -workName "${{ env.workName  }}" -workResourceGroupName "${{ env.workResourceGroupName  }}"
      - name: Deploy ${{ env.appiName  }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.rgName  }} --template-file ${{ env.armPath  }}/appi-applicationinsights.json --parameters  ${{ env.armPath  }}/appi-applicationinsights.parameters.json -name "${{ env.appiName  }}" -workName "${{ env.workName  }}" -workResourceGroupName "${{ env.workResourceGroupName  }}"
      - name: Validate ${{ env.kvName   }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.rgName  }} --template-file ${{ env.armPath  }}/kv-keyvault.json --parameters  ${{ env.armPath  }}/kv-keyvault.parameters.json -name "${{ env.kvName   }}"
      - name: Deploy ${{ env.kvName   }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az deployment group create --resource-group ${{ env.rgName  }} --template-file ${{ env.armPath  }}/kv-keyvault.json --parameters  ${{ env.armPath  }}/kv-keyvault.parameters.json -name "${{ env.kvName   }}"
