on:
  push:
    branches-ignore:
    - main
    paths:
    - .github/workflows/gtc-rg-subjects-landingzone.yml
    - .azure/**/*.json
  pull_request:
    branches:
    - main    
    paths:
    - .github/workflows/gtc-rg-subjects-landingzone.yml
    - .azure/**/*.json

env:
  API_NAME: 'api-subjects-dev-001'
  APPINSIGHTS_NAME: 'appi-subjects-dev-001'
  ARM_PATH: './.azure'
  AZURE_RG_ENVIRONMENT: 'Development'
  AZURE_RG_LOCATION: 'westus3'
  AZURE_RG_NAME: 'gtc-rg-subjects-dev-001'
  KEYVAULT_NAME: 'kv-subjects-dev-001'
  PLAN_NAME: 'plan-entities-dev-001'
  SHARED_RG_NAME: 'gtc-rg-entities-dev-001'
  STORAGE_NAME: 'stsubjectsdev001'
  WORKSPACE_NAME: 'work-entities-dev-001'  

permissions:
  id-token: write
  contents: read
  security-events: write

jobs:  
  development_Stage_deploy_landing_zone:
    name: 'Deploy landing zone IaC'
    runs-on: ubuntu-latest
    environment: development
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy ${{ env.AZURE_RG_NAME }}
        uses: Azure/cli@v1.0.0
        with:
          inlineScript: az group create -n ${{ env.AZURE_RG_NAME }} -l ${{ env.AZURE_RG_LOCATION }}
      # stPRODUCTENVIRONMENT001
      - name: Deploy ${{ env.STORAGE_NAME }}
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RG_NAME }}
          template: ${{ env.ARM_PATH }}/st-storageaccount.json
          parameters: name=${{ env.STORAGE_NAME }}
      # kv-PRODUCT-ENVIRONMENT-001
      - name: Deploy ${{ env.KEYVAULT_NAME }}
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RG_NAME }}
          template: ${{ env.ARM_PATH }}/kv-keyvault.json
          parameters: name=${{ env.KEYVAULT_NAME }}
      # appi-PRODUCT-ENVIRONMENT-001
      - name: Deploy ${{ env.APPINSIGHTS_NAME }}
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RG_NAME }}
          template: ${{ env.ARM_PATH }}/appi-applicationinsights.json
          parameters: name=${{ env.APPINSIGHTS_NAME }} workName=${{ env.WORKSPACE_NAME }} workResourceGroupName=${{ env.SHARED_RG_NAME }}
      # api-PRODUCT-ENVIRONMENT-001
      - name: Deploy ${{ env.API_NAME }}
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          resourceGroupName: ${{ env.AZURE_RG_NAME }}
          template: ${{ env.ARM_PATH }}/api-apiapp.json
          parameters: name=${{ env.API_NAME }} planName=${{ env.PLAN_NAME }} planResourceGroupName=${{ env.SHARED_RG_NAME }} appiKey=${{ secrets.APPI_KEY }} appiConnection=${{ secrets.APPI_CONNECTION }} rgEnvironment=${{ env.AZURE_RG_ENVIRONMENT }}