on:
  workflow_call:
    inputs:
      armPath:
        required: true
        type: string
      subscriptionId:
        required: true
        type: string
      subscriptionService:
        required: true
        type: string
      rgName:
        required: true
        type: string
      rgLocation:
        required: true
        type: string
      appiName:
        required: true
        type: string
      kvName:
        required: true
        type: string
      stName:
        required: true
        type: string
      workLocation:
        required: true
        type: string
      workName:
        required: true
        type: string
      workResourceGroupName:
        required: true
        type: string
      workSubscriptionId:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Authenticate to Az CLI using OIDC
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    - name: Validate ${{ inputs.parameters.stName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ inputs.parameters.rgName  }} --template-file ${{ inputs.parameters.armPath  }}/st-storageaccount.json --parameters  ${{ inputs.parameters.armPath  }}/st-storageaccount.parameters.json -name "${{ inputs.parameters.stName   }}"
    - name: Deploy ${{ inputs.parameters.stName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ inputs.parameters.rgName  }} --template-file ${{ inputs.parameters.armPath  }}/st-storageaccount.json --parameters  ${{ inputs.parameters.armPath  }}/st-storageaccount.parameters.json -name "${{ inputs.parameters.stName   }}"
    - name: Validate ${{ inputs.parameters.workName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ inputs.parameters.workResourceGroupName  }} --template-file ${{ inputs.parameters.armPath  }}/work-loganalyticsworkspace.json --parameters  ${{ inputs.parameters.armPath  }}/work-loganalyticsworkspace.parameters.json -name "${{ inputs.parameters.workName   }}"
    - name: Deploy ${{ inputs.parameters.workName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ inputs.parameters.workResourceGroupName  }} --template-file ${{ inputs.parameters.armPath  }}/work-loganalyticsworkspace.json --parameters  ${{ inputs.parameters.armPath  }}/work-loganalyticsworkspace.parameters.json -name "${{ inputs.parameters.workName   }}"
    - name: Validate ${{ inputs.parameters.appiName  }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ inputs.parameters.rgName  }} --template-file ${{ inputs.parameters.armPath  }}/appi-applicationinsights.json --parameters  ${{ inputs.parameters.armPath  }}/appi-applicationinsights.parameters.json -name "${{ inputs.parameters.appiName  }}" -workName "${{ inputs.parameters.workName  }}" -workResourceGroupName "${{ inputs.parameters.workResourceGroupName  }}"
    - name: Deploy ${{ inputs.parameters.appiName  }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ inputs.parameters.rgName  }} --template-file ${{ inputs.parameters.armPath  }}/appi-applicationinsights.json --parameters  ${{ inputs.parameters.armPath  }}/appi-applicationinsights.parameters.json -name "${{ inputs.parameters.appiName  }}" -workName "${{ inputs.parameters.workName  }}" -workResourceGroupName "${{ inputs.parameters.workResourceGroupName  }}"
    - name: Validate ${{ inputs.parameters.kvName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ inputs.parameters.rgName  }} --template-file ${{ inputs.parameters.armPath  }}/kv-keyvault.json --parameters  ${{ inputs.parameters.armPath  }}/kv-keyvault.parameters.json -name "${{ inputs.parameters.kvName   }}"
    - name: Deploy ${{ inputs.parameters.kvName   }}
      uses: Azure/cli@v1.0.0
      with:
        inlineScript: az deployment group create --resource-group ${{ inputs.parameters.rgName  }} --template-file ${{ inputs.parameters.armPath  }}/kv-keyvault.json --parameters  ${{ inputs.parameters.armPath  }}/kv-keyvault.parameters.json -name "${{ inputs.parameters.kvName   }}"
                    